name: farm-fresh-api
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          DB_HOST: localhost
          DB_USERNAME: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Ruby"
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6.3"
      -
        env:
          RAILS_ENV: test
        name: "build and run tests"
        run: "gem install bundler bundle install --path .bundle bundle exec rake db:drop db:create db:migrate bundle exec rake test"
